stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_o1_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_o1_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/stage_o1_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_o1_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_o1_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_o1_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages